name: build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17
      
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
