name: build gradle project for main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: echo "Hello, World!"

      - name: version
        run: java -version

      - name: show files
        run: ls -la

      - uses: actions/checkout@v4

      - name: show files
        run: ls -la

      - uses: gradle/actions/wrapper-validation@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17
      
      - name: Make gradlew executable
        run: chmod u+x gradlew

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
